name: bradmaclean
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Bradley MacLean
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFEFF'
    - '#282F31'
    - '#5C6F91'
    - '#BDE0FF'
    - '#87A3BD'
  brandStrength: 0.7680851
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    url: null
    item: null
